# Generated by Django 4.2.27 on 2026-01-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_servicecenter_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationamenity',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='station_amenities', to='stations.station'),
        ),
    ]
