# Generated by Django 4.2.27 on 2026-01-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_alter_stationamenity_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='state',
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='servicecenter',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='city',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='state',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='station',
            name='city',
        ),
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='state',
        ),
        migrations.RemoveField(
            model_name='station',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='station',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_centers', to='stations.address'),
        ),
        migrations.AddField(
            model_name='showroom',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='showrooms', to='stations.address'),
        ),
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='stations.address'),
        ),
    ]
