# Generated by Django 4.2.27 on 2026-04-05 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0010_alter_address_table_alter_amenity_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total cost in INR', max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station_charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stations.stationcharger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ev_bookings',
                'ordering': ['-booking_date', '-start_time'],
                'indexes': [models.Index(fields=['booking_date'], name='ev_bookings_booking_3c08c0_idx'), models.Index(fields=['station_charger'], name='ev_bookings_station_fc7ca6_idx'), models.Index(fields=['user', 'status'], name='ev_bookings_user_id_b3a0ee_idx')],
            },
        ),
    ]
