# Generated by Django 4.2.27 on 2026-04-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_add_booking_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(blank=True, help_text='The charging station this booking belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stations.station'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['station'], name='ev_bookings_station_947e7f_idx'),
        ),
    ]
