# Generated by Django 4.2.27 on 2026-04-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_showrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stations', to=settings.AUTH_USER_MODEL),
        ),
    ]
