# Generated by Django 4.2.27 on 2026-04-05 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0014_servicecenter_created_by_showroom_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this amenity', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargertype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this charger type', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
