# Generated by Django 4.2.27 on 2026-04-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_amenity_created_by_brand_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chargertype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
