# Generated by Django 4.2.27 on 2026-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_alter_user_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('service', 'Service Center'), ('customer', 'Customer')], default='admin', max_length=20),
        ),
    ]
