# Generated by Django 4.2.27 on 2026-04-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('showroom', 'Showroom Admin'), ('service', 'Service Center'), ('customer', 'Customer')], default='admin', max_length=20),
        ),
    ]
