# Generated by Django 4.2.27 on 2026-04-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('station', 'Charging Station'), ('showroom', 'EV Showroom'), ('service', 'Service Center')], max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('document_url', models.FileField(blank=True, null=True, upload_to='partner_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Registration',
                'verbose_name_plural': 'Partner Registrations',
                'db_table': 'partner_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
